"""Initial migration

Revision ID: 4afa20a7dbd2
Revises: 
Create Date: 2024-09-16 11:32:37.904960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func
from app.models.base import CoverURLType

# revision identifiers, used by Alembic.
revision: str = '4afa20a7dbd2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    schema='CategoryModel'
    )
    op.create_index(op.f('ix_CategoryModel_groups_id'), 'groups', ['id'], unique=False, schema='CategoryModel')
    op.create_table('manuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('cover_image_url', CoverURLType(), nullable=False, server_default=func.CoverURLType(sa.text('file_url'))),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    schema='GroupModel'
    )
    op.create_index(op.f('ix_GroupModel_manuals_id'), 'manuals', ['id'], unique=False, schema='GroupModel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_GroupModel_manuals_id'), table_name='manuals', schema='GroupModel')
    op.drop_table('manuals', schema='GroupModel')
    op.drop_index(op.f('ix_CategoryModel_groups_id'), table_name='groups', schema='CategoryModel')
    op.drop_table('groups', schema='CategoryModel')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
