"""add auth and posts models

Revision ID: 4e36b8be8dde
Revises: ac9cd4f97c8d
Create Date: 2024-10-04 23:59:02.461699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e36b8be8dde'
down_revision: Union[str, None] = 'ac9cd4f97c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
