"""Initial migration

Revision ID: b277795f48aa
Revises: 
Create Date: 2024-09-14 08:04:17.470489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b277795f48aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('manuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('cover_image_url', sa.String(), nullable=False),
    sa.Column('category_id', sa.NullType(), nullable=True),
    sa.Column('group_id', sa.NullType(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_manual_category', use_alter=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='fk_manual_group', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuals_id'), 'manuals', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.NullType(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_group_category', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_manuals_id'), table_name='manuals')
    op.drop_table('manuals')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
